"""Bounded Design profile for the mobile checkout fixture."""

from .profile import (
    DESIGN_CONTRACT,
    DESIGN_ADJUDICATION_AUTHORITY,
    DESIGN_EVIDENCE_AUTHORITY,
    DESIGN_LAW,
    DESIGN_REFERENTS,
    DESIGN_RELATIONS,
    DESIGN_RELATION_NAMES,
    design_commitments_conflict,
    load_design_law,
)
from .authority import (
    AdjudicationAuthorityConfiguration,
    EvidenceAuthorityBinding,
    EvidenceAuthorityConfiguration,
    load_adjudication_authority,
    load_evidence_authority,
)
from .governance import (
    AuthoritativeLawSources,
    COMPILER_ID,
    GeneratedObligation,
    GovernanceBinding,
    GovernanceProfile,
    GovernedDimension,
    LawRuleProvenance,
    LawSource,
    ProposedGovernanceLaw,
    adopt_governance_law,
    compile_governance_law,
    select_authoritative_sources,
    write_obligation_artifact,
)
from .structure import (
    FrontendStructure,
    NodeSelector,
    StructuralNode,
    extract_frontend_structure,
)

__all__ = [
    "DESIGN_CONTRACT",
    "DESIGN_ADJUDICATION_AUTHORITY",
    "DESIGN_EVIDENCE_AUTHORITY",
    "DESIGN_LAW",
    "DESIGN_REFERENTS",
    "DESIGN_RELATIONS",
    "DESIGN_RELATION_NAMES",
    "design_commitments_conflict",
    "load_design_law",
    "EvidenceAuthorityBinding",
    "EvidenceAuthorityConfiguration",
    "AdjudicationAuthorityConfiguration",
    "load_adjudication_authority",
    "load_evidence_authority",
    "AuthoritativeLawSources",
    "COMPILER_ID",
    "FrontendStructure",
    "GeneratedObligation",
    "GovernanceBinding",
    "GovernanceProfile",
    "GovernedDimension",
    "LawRuleProvenance",
    "LawSource",
    "NodeSelector",
    "ProposedGovernanceLaw",
    "StructuralNode",
    "adopt_governance_law",
    "compile_governance_law",
    "extract_frontend_structure",
    "select_authoritative_sources",
    "write_obligation_artifact",
]
